language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install: "pip install greenlet cython --use-mirrors"
# command to run tests
script: cd greentest && python testrunner.py
