language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - EXTRA=1
  - GEVENTSETUP_EV_VERIFY=3
  - GEVENT_FILE=thread
  - GEVENT_BACKEND=select GEVENTSETUP_EV_VERIFY=3
  - GEVENT_BACKEND=poll GEVENTSETUP_EV_VERIFY=3
  - GEVENT_BACKEND=signalfd
#  - GEVENT_BACKEND=nosigmask
#  - GEVENT_BACKEND=noinotify
matrix:
 allow_failures:
  - env: GEVENT_BACKEND=signalfd
install:
 - deactivate
 - export VER=$TRAVIS_PYTHON_VERSION
 - export PYTHON=/usr/bin/python$VER
 - echo $PYTHON && $PYTHON --version
 - sudo -E ./travis_install_deps.sh
 - sudo $PYTHON setup.py install
script:
 - cd greentest && $PYTHON testrunner.py --full --expected ../known_failures.txt
notifications:
  email:
    recipients:
      - denis.bilenko@gmail.com
    on_success: change
    on_failure: change
