language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
#  - "3.2"
install:
 - pip install cython -q --user-mirrors
 - cython --version
 - pip install greenlet --use-mirrors
 - python setup.py install
script: cd greentest && python testrunner.py
